# The following are pulled from env variables
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  [
    {
      'source': 'src/locales/en-US/grafana-clock-panel.json',
      'translation': 'src/locales/%locale%/%original_file_name%',
      'type': 'i18next_json',
    },
  ]