name: Crowdin Upload Action

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/locales/en-US/grafana-clock-panel.json'
    branches:
      - main

jobs:
  upload-sources-to-crowdin:
    uses: grafana/grafana-github-actions/.github/workflows/crowdin-upload.yml@main
    with:
      crowdin_project_id: 36
