name: Crowdin Download Action

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  download-sources-from-crowdin:
    runs-on: ubuntu-x64
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Get GitHub App token
        id: get-github-app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@259ba21cb3ff07724f331e26d926d655d24b317b # create-github-app-token/v0.2.3
        with:
          github_app: grafana-pr-automation
      - name: 'Get vault secrets'
        id: vault-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@main
        with:
            # Vault secret paths:
            # - ci/repo/grafana/clock-panel/grafana-frontend-crowdin-token
            repo_secrets: |
                CROWDIN_TOKEN=grafana-frontend-crowdin-token:access_token
      - name: Download from Crowdin
        uses: grafana/grafana-github-actions/crowdin-download@main
        with:
          crowdin_token: ${{ env.CROWDIN_TOKEN }}
          crowdin_project_id: 36
          pr_labels: 'i18n'
          github_board_id: 76 # Plugins Platform / Grafana Community project
          github_repo_token: ${{ steps.get-github-app-token.outputs.token }}
