name: Crowdin automatic task management

on:
  workflow_dispatch:
  # once a month on the first day of the month at midnight
  schedule:
    - cron: '0 0 1 * *'

jobs:
  create-tasks-in-crowdin:
    uses: grafana/grafana-github-actions/.github/workflows/crowdin-create-tasks.yml@9fcaf3ce23a43128b51a0120968e0f0d25298cf5
    with:
      crowdin_project_id: 36
    
    permissions:
      contents: read
      id-token: write # needed to get vault secrets
