name: Plugins - CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  ci:
    name: CI
    uses: grafana/plugin-ci-workflows/.github/workflows/ci.yml@20fb6712683551af8d4b69e9a35f4bcdff8c2535 # ci-cd-workflows/v5.1.0
    permissions:
      contents: read
      id-token: write
    with:
      plugin-version-suffix: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
      run-playwright-with-grafana-dependency: '>=11.0.0'
      node-version: '24'
